# 自定义配置
lux:
  # 项目主机连接地址
  address: http://127.0.0.1
#  address: http://8.130.104.52
  # 项目名称
  chatroom-name: IM
  # 功能属性
  entities:
    # 注册功能
    sign-up:
      # 是否启用（是否开放注册功能）
      enabled: true

    # 重置账户密码功能（是否开放重置账户密码功能）
    reset-password:
      enabled: true

server:
  port: 80
  servlet:
    context-path: /chatroom
    encoding:
      charset: utf-8
      force: true
      enabled: true
    session:  # 取消session的永久存储，以免程序抛出：Exception loading sessions from persistent storage
      persistent: false

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/chatroom?allowMultiQueries=true
#    url: jdbc:mysql://8.130.104.52:3306/chatroom?allowMultiQueries=true
    username: root
    password: xmq154656

  mail:
    # 邮件服务器
    host: smtp.163.com
    # 端口号
    port: 25
    # 发件人邮箱地址
    username: loveislonging@163.com
    # 邮箱的SMTP授权码
    password: MWRSYWMJMZYGQFAC
    properties:
      mail:
        smtp:
          # 开启权限验证
          auth: true
          # 开启超时连接即断开
          connectiontimeout: 5000
          # 开启超时设置
          timeout: 3000
#          开启debug模式
#        debug: true
  thymeleaf:
    cache: true

mybatis:
  mapper-locations: classpath:mybatis/mapper/*.xml                  # 指定sql映射文件的位置
  configuration:    # 指定MyBatis全局配置文件中的相关配置项
    map-underscore-to-camel-case: true    # 开启驼峰命名